CREATE DATABASE IF NOT EXISTS SP_lab1;
USE SP_lab1;
CREATE TABLE IF NOT EXISTS users(
	id INT UNSIGNED AUTO_INCREMENT,
  usr_name VARCHAR(100) NOT NULL,
	pwd VARCHAR(100) NOT NULL,
	Tname VARCHAR(100) NOT NULL,
	student_num VARCHAR(20) NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS messages(
	id INT UNSIGNED AUTO_INCREMENT,
	usr_name VARCHAR(100) NOT NULL,
	msg VARCHAR(200),
	time TIMESTAMP NOT NULL,
	channel_name VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS channel(
	id INT UNSIGNED AUTO_INCREMENT,
	channel_name VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO users (usr_name,pwd,Tname,student_num)
VALUES ('admin','21232f297a57a5a743894a0e4a801fc3','admin','admin');

INSERT INTO channel (channel_name)
VALUES ('default channel');
